version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: CONTAINER_TOTEMDB
    environment:
      MYSQL_DATABASE: 'totembd'
      MYSQL_PASSWORD: 'urubu100'
      MYSQL_ROOT_PASSWORD: 'urubu100'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
